export const genreList = {
  1: {
    id: 1,
    name: 'Action',
    isChecked: false,
  },
  2: {
    id: 2,
    name: 'Adventure',
    isChecked: false,
  },
  3: {
    id: 3,
    name: 'Animation',
    isChecked: false,
  },
  4: {
    id: 4,
    name: 'Comedy',
    isChecked: false,
  },
  5: {
    id: 5,
    name: 'Crime',
    isChecked: false,
  },
}

export const movieList = [
  {
    id: 1,
    vote_average: 6.5,
    title: 'Venom',
    popularity: 423.154,
    poster_path: '/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg',
    genre_ids: [1, 2],
    release_date: '2018-10-03',
  },
  {
    id: 2,
    vote_average: 7,
    title: 'Fantastic Beasts: The Crimes of Grindelwald',
    popularity: 220.606,
    poster_path: '/uyJgTzAsp3Za2TaPiZt2yaKYRIR.jpg',
    genre_ids: [3, 4],
    release_date: '2018-11-14',
  },
  {
    id: 3,
    vote_average: 8.2,
    title: 'Bohemian Rhapsody',
    popularity: 211.565,
    poster_path: '/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg',
    genre_ids: [5],
    release_date: '2018-10-24',
  },
  {
    id: 4,
    vote_average: 5.9,
    title: 'Mortal Engines',
    popularity: 201.549,
    poster_path: '/uXJVpPXxZO4L8Rz3IG1Y8XvZJcg.jpg',
    genre_ids: [1],
    release_date: '2018-12-06',
  },
  {
    id: 5,
    vote_average: 6,
    title: 'Robin Hood',
    popularity: 171.519,
    poster_path: '/AiRfixFcfTkNbn2A73qVJPlpkUo.jpg',
    genre_ids: [2],
    backdrop_path: '/AuA50D7T7S7OEVcGo0ZKaMhERn0.jpg',
    release_date: '2018-11-20',
  },
  {
    id: 6,
    vote_average: 5.9,
    title: 'The Seven Deadly Sins: Prisoners of the Sky',
    popularity: 150.182,
    poster_path: '/r6pPUVUKU5eIpYj4oEzidk5ZibB.jpg',
    genre_ids: [3],
    release_date: '2018-08-18',
  },
  {
    id: 7,
    vote_average: 7.5,
    title: 'Ralph Breaks the Internet',
    popularity: 141.193,
    poster_path: '/m110vLaDDOCca4hfOcS5mK5cDke.jpg',
    genre_ids: [4, 5],
    release_date: '2018-11-20',
  },
]
